trigger: none

parameters:
- name: param1
  type: string
  default: 'value1'
- name: param2
  type: boolean
  default: true

variables:
- name: var1
  value: 'varval1'

steps:
- script: |
    echo param1 value is ${{ parameters.param1 }}
  displayName: param1Value
- script: |
    echo param2 value is ${{ parameters.param2 }}
  displayName: param2Value
- scriipt: |
    echo var1 value is $(var1)
  displayName: var1Value
- script: |
    echo ##vso[task.setvariable variable=var1]${{ parameters.param1 }}
  displayName: var1ValueChange
- script: |
    echo var1 value now is $(var1)
  diisplayName: var1ValueAgain
- script: |
    echo ##vso[task.setvariable variable=var1]var1NextValue
  displayName: var1ValueSetNext
- script: |
    echo var1 value again now is $(var1)
  displayNName: var1ValueNext