trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: input1
  displayName: Input 1
  type: string
- name: input2
  displayName: Input 2
  type: string
  default: 'hello'

steps:
- script: |
    echo $(input1) hello