trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: A
  jobs:
  - job: A
    steps:
    - script: echo A
- stage: B
  # this make this stage runs only if previous stage fails
  condition: failed()
  jobs:
  - job: B
    steps:
    - script: echo B
- stage: C
  # this makes this stage run only if B stage succeeded
  condition: succeeded('A')
  jobs:
  - job: C
    steps:
    - script: echo C
    - script: exit 1
- stage: D
  # dependsOn and condition are interrelated i.e. condition is evaluated on the dependsOn stages.
  dependsOn: A
  condition: failed()
  jobs:
  - job: D
    steps:
    - script: echo D
