trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildAndTest
  jobs:
  - job: Build
    steps:
    - script: echo Built the app
  - job: Test
    # this job depends on Build job
    dependsOn: Build
    steps:
    - script: echo Testing the app
- stage: DeployUS1
  # This stage depends on BuildAndTest stage
  dependsOn: BuildAndTest
  jobs:
  - job: Deploy
    steps:
    - script: echo Deployed to US1 region
- stage: DeployUS2
  # This stage depends on BuildAndTest stage
  dependsOn: BuildAndTest
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying to US2 region
- stage: DeployUS3
  # dependsOn can be mentioned as list also
  dependsOn:
  - BuildAndTest
  - DeployUS1
  - DeployUS2
  jobs:
  - job: Deploy
    steps:
    - script: echo Deployed to US3 region
