trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildAndTest
  jobs:
  - job: Build
    steps:
    - script: echo Built the app
  - job: Test
    dependsOn: Build
    steps:
    - script: echo Testing the app
- stage: DeployUS1
  dependsOn: BuildAndTest
  jobs:
  - job: Deploy
    steps:
    - script: echo Deployed to US1 region
- stage: DeployUS2
  dependsOn: BuildAndTest
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying to US2 region
- stage: DeployUS3
  dependsOn:
  - BuildAndTest
  - DeployUS1
  - DeployUS2
  jobs:
  - job: Deploy
    steps:
    - script: echo Deployed to US3 region
