trigger: none

variables:
- name: var1
  value: initialValue

steps:
- script: |
    echo ${{ variables.var1 }} # prints initialValue
- script: |
    echo "##vso[task.setvariable variable=var1]secondValue"
- script: |
    echo ${{ variables.var1 }} # prints initialValue
    echo $(var1) # prints secondValue